version: '3'

services:
  milon:
    build: .
    ports:
      - "5431:5431"
    volumes:
      - .:/milon
    restart: always
    depends_on:
      - db
    command: ["/venv/bin/python", "/milon/source/main.py"]

  db:
    build: db_docker
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
      MADRASA_SERVER_KEY_SECRET_DEV: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  db_data: